### ISSUE TITLE
Typo in readme foarmtEmailAddress => formatEmailAddress

### ISSUE THREAD

**Issue by niftylettuce** [LinusU/format-email-address#1]

**Comment by niftylettuce** [comment]
also you might want to use lass for future projects! <https://lass.js.org/#/>

**Comment by LinusU** [comment]
Looks interesting, would be nice with an option to use `standard` instead of `xo` though 😄

**Comment by niftylettuce** [comment]
@LinusU you should subscribe to <https://github.com/lassjs/lass/issues/29>
